square = int(input("What is the length of a side of the square? "))
print(f"The area of the square is: {square ** 2}")
length_rectangle = int(input("What is the length of rectangle? "))
width_rectangle = int(input("What is the width of the rectangle? "))
print(f"The area of the rectangle is: {length_rectangle * width_rectangle}")
radius = int(input(f"What is the radius of the circle? "))
print(f"The area of the circle is: {2 * radius * 3.14}")
radius = int(input(f"What is the radius of the circle? "))
print(f"The area of the circle is: {math.pi * radius*2}")